image: adoptopenjdk/openjdk11:alpine

stages:
  - build

before_script:
  - chmod +x mvnw

build:
  stage: build
  script: ./mvnw package
  artifacts:
    paths:
      - target/health-helper-service-0.0.1-SNAPSHOT.jar
