version: '3.1'

services:

  health-helper-service:
    image: health-helper-service:0.0.1-SNAPSHOT
#    build:
#      context: .
    container_name: health_helper_service
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/health-helper-db
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      FILE_SHARING_SECURITY_JWT_SECRET: ${JWT_SECRET}
      FILE_SHARING_SECURITY_ADMINS_VOIDASPECT_PASSWORD: ${DEFAULT_ADMIN_PASSWORD}
    depends_on:
      - db
    ports:
      - 8080:8080

  db:
    image: postgres:13
    container_name: health-helper-db
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: health-helper-db
      TZ: UTC
      PGTZ: UTC
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  db-data:
    driver: local

