server:
  http2:
    enabled: true
  error:
    include-message: always
    include-binding-errors: always

health-helper:
  security:
    jwt:
      secret: eitu9aichae7eitee9XiciweishohW3pieshaifasosai5xie9Oomobulohyu8ie
      expire-in: 3600000
    admins:
      pupchenkoa:
        email: pupchenkoa@ukr.net
        password: 123

springdoc:
  show-login-endpoint: true

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/health-helper-db
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 3176rz1t
  jpa:
    open-in-view: false
    hibernate:
      show-sql: true
#      ddl-auto: update
#    generate-ddl: true

management:
  endpoint:
    health:
      show-details: when_authorized
